steps:
  - label: ':docker: Build & Push'
    plugins:
      - https://github.com/obrin/buildkite-container-plugin.git#v1.0.0:

  - wait

  - label: ':rocket: Deploy'
    plugins:
      - https://github.com/obrin/buildkite-deploy-plugin.git#v1.0.9:
